### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by neightyy** [pterobilling/pterobilling#58] opened 2021-04-18 22:55 UTC
So if panel does only English language, why not add more?
It's great idea, and more people will use that framework.

**Comment by MinePlay85** [comment] 2021-04-18 22:59
Hello,
Good idea but it's already planed for the release 1.0.
But I can do it but only French language because i learned french.

**Comment by neightyy** [comment] 2021-04-18 23:32
I can do Polish language, cuz i'm from Poland so, it's good.

**Comment by AlaisterLeung** [comment] 2021-04-19 01:41
Duplicate of #36

**Closed** 2021-04-19 01:41 UTC
Labels: duplicate, enhancement
